name: Test Check Domains Script

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4.2.2
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y dnsutils bind9-utils
      - name: Make script executable
        run: chmod +x check_domains.sh
      - name: Run check_domains.sh
        run: ./check_domains.sh --file domains.txt